spring:
  application:
    name: nicht-die-bohne
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: admin123
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
